### ISSUE TITLE
can't withdraw balance & http status is 200 Ok

### ISSUE THREAD

**Issue by renepickhardt** [Horndev/zapread.com-issues#38]
so my balance is 784 I created an invoice of 749 but it is not processed. In my third try I get an error message after about 72 seconds. But it just says: Error processing request... however the http status is 200 Ok which is wrong from a semantical point of view

the invoice reads: 
lnbc7490n1pdc949gpp5pmdxdleun64tw57p9uatphsvpmvwfxp6auuk9aqd8drunw9qzqksdpswd6xjmrv94skuttpwajhxmmdv5khx6t5v5kkcmmkd9hz66t5cqp2c25hxj3d2d62mnlqev6zx8paxexucq7zq2h8pkury0sucutp6lgs26n0am87zzgh8cgf7ruxargwjwjr6895gd5fadd8yh270f5nlqcp8zte4y

**Comment by Horndev** [comment]
I've added some logging for this.  Try a withdraw again.  There are two possible causes - 1 is an unhandled exception, 2 is that the user lookup in the DB failed.

I was having some problems with my lnd back end yesterday, which fixed itself.  Not sure what was causing it.  It could be the lnd invoice database is getting big?  I should get better logging next time it happens.

I don't reveal information on withdraws (not even HTTP codes) on purpose in order to prevent leaking information to anyone trying to "hack" in.

**Comment by renepickhardt** [comment]
did work yesterday night. can't give you any more information. 

I don't get the argument with http status codes

**Comment by Horndev** [comment]
Probably a LND routing error.  Closing issue for now.
