### ISSUE TITLE
Shamless self bump payout algo?

### ISSUE THREAD

**Issue by camo0067** [Horndev/zapread.com-issues#81]
![shamless self bump](https://user-images.githubusercontent.com/42921424/44997353-4b0c5780-af73-11e8-9476-c689df0d5b1b.png)

the algo is set to not reward self bumping?

**Comment by Horndev** [comment]
The more I think about it, the more I like the concept of self-bumping going to the community.  Basically, it's like advertising - but you get paid for having to see the advertisement.  If someone pays to bump up their own post, all of the other posts are compensated.  

**The problem** is how to actually implement this.  Right now, you can make anonymous payments on LN, and if someone self-promotes anonymously, then yes, the money goes back to their account.  I also can't test for pub_keys since the originator of the payment is not known in LN.  (privacy-preserving).

I guess, for now, we have to accept that 60% goes back to the person advertising, and 40% goes to users and zapread.
